// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ctron_xcorr1
NumericVector ctron_xcorr1(const NumericVector& x, const NumericVector& y);
RcppExport SEXP convotron_ctron_xcorr1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    __result = Rcpp::wrap(ctron_xcorr1(x, y));
    return __result;
END_RCPP
}
// ctron_conv1
NumericVector ctron_conv1(const NumericVector& x, const NumericVector& y);
RcppExport SEXP convotron_ctron_conv1(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    __result = Rcpp::wrap(ctron_conv1(x, y));
    return __result;
END_RCPP
}
// ctron_fftfilt
NumericVector ctron_fftfilt(const NumericVector& x, const NumericVector& y, bool corr);
RcppExport SEXP convotron_ctron_fftfilt(SEXP xSEXP, SEXP ySEXP, SEXP corrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< bool >::type corr(corrSEXP);
    __result = Rcpp::wrap(ctron_fftfilt(x, y, corr));
    return __result;
END_RCPP
}
