# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctron_xcorr1 <- function(x, y) {
    .Call('convotron_ctron_xcorr1', PACKAGE = 'convotron', x, y)
}

ctron_conv1 <- function(x, y) {
    .Call('convotron_ctron_conv1', PACKAGE = 'convotron', x, y)
}

ctron_fftfilt1 <- function(x, y, corr) {
    .Call('convotron_ctron_fftfilt1', PACKAGE = 'convotron', x, y, corr)
}

ctron_fftfilt1mx <- function(x, y, corr) {
    .Call('convotron_ctron_fftfilt1mx', PACKAGE = 'convotron', x, y, corr)
}

ctron_xcorr1mx <- function(x, y) {
    .Call('convotron_ctron_xcorr1mx', PACKAGE = 'convotron', x, y)
}

ctron_conv1mx <- function(x, y) {
    .Call('convotron_ctron_conv1mx', PACKAGE = 'convotron', x, y)
}

